name: Docker Build Image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.lagoland.xyz
          username: ${{ gitea.actor }}
          password: ${{ secrets.USER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@master
        with:
          push: true
          tags: gitea.lagoland.xyz/${{ gitea.repository }}:latest
      